#!/usr/bin/env node
// Regenerates src/catalogData.js (the bundled, cache-proof catalog the app
// actually loads at runtime) from the single canonical 90s_playlist.csv.
//
// Run this after editing 90s_playlist.csv: npm run build-catalog

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Papa from 'papaparse';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const csvPath = path.join(root, '90s_playlist.csv');
const catalogOutPath = path.join(root, 'src', 'catalogData.js');
const publicCsvPath = path.join(root, 'public', '90s_playlist.csv');

const csvText = fs.readFileSync(csvPath, 'utf8');
const parsed = Papa.parse(csvText, { header: true, skipEmptyLines: true });

if (parsed.errors.length > 0) {
  console.error('CSV parse errors:', parsed.errors);
  process.exit(1);
}

const rows = parsed.data.map(row => ({
  decade: (row.decade || '1990s').trim(),
  year: (row.year || '1995').trim(),
  channel: (row.channel || 'Commercials').trim(),
  video_id: (row.video_id || '').trim(),
  title: (row.title || '').trim(),
  start_seconds: (row.start_seconds || '0').toString().trim() || '0',
  end_seconds: (row.end_seconds || '0').toString().trim() || '0'
}));

const missingIds = rows.filter(r => !r.video_id);
if (missingIds.length > 0) {
  console.error(`${missingIds.length} row(s) are missing a video_id. Fix 90s_playlist.csv and re-run.`);
  process.exit(1);
}

const ids = rows.map(r => r.video_id);
const dupes = [...new Set(ids.filter((id, i) => ids.indexOf(id) !== i))];
if (dupes.length > 0) {
  console.warn(`Warning: duplicate video_id(s) in 90s_playlist.csv: ${dupes.join(', ')}`);
}

const banner =
  '// AUTO-GENERATED by `npm run build-catalog` from 90s_playlist.csv.\n' +
  '// Do not hand-edit this file — edit 90s_playlist.csv and regenerate.\n' +
  'export const DEFAULT_90S_CATALOG = ';

fs.writeFileSync(catalogOutPath, banner + JSON.stringify(rows, null, 2) + ';\n');
fs.copyFileSync(csvPath, publicCsvPath);

console.log(`Wrote ${rows.length} videos to src/catalogData.js and synced public/90s_playlist.csv`);
