// AUTO-GENERATED by `npm run build-catalog` from 90s_playlist.csv.
// Do not hand-edit this file — edit 90s_playlist.csv and regenerate.
export const DEFAULT_90S_CATALOG = [
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "kX8ARC24ZCE",
    "title": "1990 Kellogg's Frosted Flakes \"That's a kids cereal\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "omzspZYMG-o",
    "title": "3/4/90 | TBS Commercials & Promos",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "wSDoBwroREM",
    "title": "1990 Nestle TollHouse Morsels \"Perkins Women Secret\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "GnYjybANG9A",
    "title": "1990 week 1 Dolphins at Patriots",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "d8iKN2Yf73s",
    "title": "ATWT 3 9 90",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "DUx7dP2S7h4",
    "title": "The Computer Chronicles - High Tech France Part 1 (1990)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "fh-aTZoNdjQ",
    "title": "ITT We Built this Business commercial 1990",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "GAlRLwyEJIU",
    "title": "The Bean Test | Funny Episodes | Mr Bean Official",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "EkCAh_cxBes",
    "title": "News 12 coverage (October 1990)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "9o3jq9s0sYc",
    "title": "Match Game (#003):   July 18, 1990 (Premiere Week)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "kDVhc-VrlQw",
    "title": "One Network News Update 1990",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "SGdGVlyaKJ8",
    "title": "The Simpsons - Krusty The Clown & Kent Brockman",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "coL71N438p0",
    "title": "Circus Of Power - Vices (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "YlkJA9XWyKI",
    "title": "Green Jello - Nightmare on Sesame Street",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "fL-k14W7vug",
    "title": "Spotlight: Independence Dogs (WHYY, 1990)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "0eobDklCOMc",
    "title": "MISS WORLD 1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "ojcHGjldn8k",
    "title": "Mouse Trap Board Game Ad (1991) (on-screen text)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "6d1eyDZbjTE",
    "title": "KCCI TV-8 News at Ten (February 27, 1991)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "0sOL7dkXaPw",
    "title": "WHO-TV NBC commercials (April 28, 1991)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "CWJ3Y0wlcGI",
    "title": "Frank Davis Fish n' Game Report Promo WWL-TV CH4 1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "ATg2EzvTftQ",
    "title": "1991 Lexus ES250 Lease TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "eaG9mARgp64",
    "title": "1991 Leggs Classics Pantyhose TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "Wf1nemeR0q4",
    "title": "1991 Pizza Hut \"Supreme 4 Bucks Deal\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "EoEn7N5dGFU",
    "title": "TNT commercial break 5 - 1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "XCULJDQfnus",
    "title": "House Party II TV Spot (1991)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "ygG97KbFAQI",
    "title": "JACK GALLAGHER - LOL STAND-UP ON 'ARSENIO'",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "KpOsMDlRRP4",
    "title": "Classic Concentration 20 June 1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "MUuNDb-nm5M",
    "title": "Michael Bolton - When a Man Loves a Woman (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "-w6YDPWfE_8",
    "title": "Minute Maid Orange Soda featuring Isiah Thomas | Television Commercial | 1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "X3QLqgeNz34",
    "title": "Homefront season 1 intro, version 2",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "81PwCrg4Pcg",
    "title": "Kroger \"Listen to the Scissors\" Commercial (1992)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "02W2gWBBNDk",
    "title": "Global commercials (February 1992), Read Description",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "4JFRdJTszRM",
    "title": "The Bodyguard (1992) Official Trailer - Kevin Costner, Whitney Houston Movie HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "GK6QQY4ZpJM",
    "title": "1992 Chrysler Lee Iacocca Reorganized TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "OPkWYTUiPTo",
    "title": "Eric B. & Rakim - Juice (Know The Ledge)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "aWKpfRiQhyM",
    "title": "Dairy Queen Chicken Sandwich Commercial (1992)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "gdbysPaB_Dc",
    "title": "Shoney's new shrimp dinners & deserts 1992 Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "kKyat5psfss",
    "title": "CBC 1992 Commercial Break #4",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "kXNLVmnYIEk",
    "title": "Dinosaurs TV Show Toy Commercial (1992)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "VR1g9jI9tuk",
    "title": "1992   Raiders  at  Dolphins  MNF   Week 15",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "KpkLccLcC0g",
    "title": "Thompsons Water Seal Commercial 1992",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "yY81juUn_Ho",
    "title": "Channel 4 | Remote Control | Football Special | 23rd April 1992",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "YMUFLbpCpKM",
    "title": "1992 Penguins Stanley Cup Celebration",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "IrWFDSyO0H8",
    "title": "Hell's Kitchen AIDS Project (1992) and Essays (1994, NY1 News)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "-Q2pppcNURI",
    "title": "1992   MLB Highlights   June 7-9",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "yeysTuID5qc",
    "title": "1993 Celestial Teas Iced Delight Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "KPY0hHYuU4g",
    "title": "CityTV Bumper featuring legendary Toronto busker Ben Kerr (1993)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "sGiSx0TYwVg",
    "title": "1990's TV Commercials: Volume 71",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "RDR3xMJ5Jf4",
    "title": "1993 Sega CD \"You still don't have a SEGA CD?\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "wGhaWdY1Gho",
    "title": "WHEC-TV News at 6 - April 2, 1993",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "gGLHOE6koEg",
    "title": "1993   MLB Highlights   September 13-14",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "NjHpay2E94s",
    "title": "AWOL - Postcards",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "EfiCQTety78",
    "title": "WHO-TV Wheel of Fortune \"Wheel Deal\" promo (1993)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "1xBuSRjgE-Y",
    "title": "WeatherStar 4000, JFK, 1993",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "Q0a0QwWuTEA",
    "title": "A Bronx Tale - Working Man - (1993)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "UhvxRWnnTIE",
    "title": "FURBOWL desertion VIDEOCLIP",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "za_kV57a9sQ",
    "title": "The Legends of Treasure Island Ep.4 Now You See Me",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "7ETTl5tOECs",
    "title": "Global News \"The World Tonight\" - February 10th, 1993",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "UrPGQi-9c_k",
    "title": "[HQ] Mariah Carey - Hero ( Live - 1993 )",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Drama",
    "video_id": "DxALqzLedw4",
    "title": "1993   Bears  at  Chiefs   Week 12",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "m3SWeB5FCOM",
    "title": "1994 Nissan Altima \"Like the Lexus LS400\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "CbZNgzqZpyU",
    "title": "Words and Pictures: W (1994) - FULL EPISODE",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "wYyBA0JjXpM",
    "title": "Johnson's Baby Shampoo (1994) Television Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "-1J6MOxYCWQ",
    "title": "Charlie Red by Revlon Television Commercial 1994 featuring Karen Duffy",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "i4-bUYU3BH8",
    "title": "KMFDM - A Drug Against War ‌‌ - Bohemia Afterdark",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "ONxkhsVfVQc",
    "title": "NBC Commercials (February 13, 1994) - Part 2 of 2",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "kSoo18REKe0",
    "title": "Dumb and Dumber (1994) Trailer | Jim Carrey | Jeff Daniels",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "dri3JL2y6i8",
    "title": "CBS/WFMY Commercials November 15, 1994 Part 3",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "-6i4MvXFIRc",
    "title": "Photon: The Ultimate Game On Planet Earth Laser Tag Soundtrack",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "47x7dC_nXKw",
    "title": "My Iron Lung - Radiohead",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Bq7FYvhAy0M",
    "title": "Martin Short on 'Regis & Kathie Lee' show, 1994",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "qMjcDVEFQDs",
    "title": "In the Mouth of Madness (1994) Trailer | Sam Neill | Jürgen Prochnow",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Aw0Bywq1wf0",
    "title": "Wendy's (1994) Television Commercial - JR Bacon Cheeseburger",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "M9wK6PGG6-Y",
    "title": "Quick Cream of Wheat Commercial (1994)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "8R__2z8F1Lo",
    "title": "Dumb and Dumber (1994) - Unrated Edition Trailer",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "Z-lEU3PAtUQ",
    "title": "1995   ESPN Plays of the Week   November 26",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "pKveOqw5ukY",
    "title": "The Roots - Silent Treatment",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "cv7NEbacamQ",
    "title": "Nick Cave & The Bad Seeds - Where The Wild Roses Grow (Live at Koko) ft. Kylie Minogue",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "q821IwcSpag",
    "title": "Under One Roof (1995) - Episode 5 - Secrets",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "aW2RahBfVso",
    "title": "1995   Vikings  at  Bengals   Week 17",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "Mo2E2WSqjgE",
    "title": "Duracell 1995 Commercial #2",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "h7HuzExIJwQ",
    "title": "Disney's Sing Along Songs (1995) Television Commercial - Pocahontas -VHS - Home Video",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "cyUn5HNbZgM",
    "title": "Kroger Commercial with UofL Football Coach Ron Cooper (1995)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "BMjk8ue3JlA",
    "title": "DirecTV 1995 Partial Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "3vFs7LrlcUM",
    "title": "Budgie The Little Helicopter S1Ep21 Deep Sleep",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "POsybK6lK9o",
    "title": "SuperAmerica Gas Station Commercial (1995)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "XFqv-QOSDfg",
    "title": "BROOKE SHIELD'S FAMOUS CHERRY STEM KNOT on 'LENO'",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "V2Q40rXJuMU",
    "title": "Billy Madison Official Trailer #1 - Adam Sandler Movie (1995) HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "a7yQIH0YSjg",
    "title": "1995 Levi's 501 Jeans \"Reason #007\" \"Trade them for a car\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Kids",
    "video_id": "iA4r8e6It6Y",
    "title": "WNBC 6pm Newscast (April 8, 1995; A and C Blocks)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "ZiPgbBSwhi0",
    "title": "1996 Domino's *NEW* Garlic Crunch Crust Pizza TV commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "v0wKRYSgYrA",
    "title": "1996 Tide Liquid Detergent \"Quadruplets\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "p43HvPLaAOs",
    "title": "Oakland Raiders at NY Jets 2nd half week 6 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "4S3d9UdJrvg",
    "title": "1996   Bills  at  Giants   Week 1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "56s9cQSfBsc",
    "title": "FOX Commercials - April 30, 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "jV8vyvnwaII",
    "title": "Babe Pay-Per-View & McDonald's Happy Meal Poster Tie-In Ad (1996)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "N0aAA0KnlGo",
    "title": "Metallica - The House Jack Built",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "MKIxeA3waFg",
    "title": "1996 Kinko's Commercial: Pool Management Business - Aired November 27, 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "YFdSs2beNyg",
    "title": "KFC Roasted Chicken and Crispy Strips Commercial (1996)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "2NbQFdUuzjI",
    "title": "Black & Decker Snake Light Dion The Wanderer Christmas commercial 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "wyiTbaMfwpI",
    "title": "Honey Frosted Wheaties featuring Deion Sanders | Television Commercial | 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "l974a0bb398",
    "title": "Mo Thugs - Thug Devotion",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "pk-pQYXxHOw",
    "title": "Vince McMahon interviews Shawn Michaels after winning the WWF Title at Wrestlemania XII. 1996",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "FSBaIxoj68U",
    "title": "Bulletproof Movie Trailer 1996 - TV Spot  Adam Sandler, Damon Wayans",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "JQvUUNnMfbw",
    "title": "M&M's - Pool (1996, USA)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "_0TxTKo_LyM",
    "title": "Gattaca Movie Trailer 1997 - TV Spot",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "IdipMQLPlJM",
    "title": "CBS | CBS Morning News | October 14, 1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "nhrLR8ZW0Qc",
    "title": "Chris Farley Monologue - Saturday Night Live",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "d_e4RLUAm3g",
    "title": "The Computer Chronicles - SPA Codie Awards 1997 (1997)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "5gpqT-PwjyM",
    "title": "First interleague regular season game Mets at Yankees June 16 1997 a few newsclips and the final out",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "iBBqjGd3fHQ",
    "title": "Creed - My Own Prison (Official HD Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "x75VlyfUZnQ",
    "title": "Nickelodeon kid talks about his week short 1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "syIKh3fSe7A",
    "title": "Mitch Hedberg on Turkeys, Tennis, and Turtlenecks | Letterman",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "x2gCgqcHdGs",
    "title": "1997 Divisional Round Vikings @ 49ers 2nd Half",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "BgqSiYXgUX0",
    "title": "Weather Channel clips including Local Forecasts, Monday July 28 1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "iKjBrB0iRFQ",
    "title": "Unsolved Mysteries with Robert Stack - Season 9 Episode 15 - Full Episode",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "iCkUr1T5Wa8",
    "title": "Sniz and fondue  hosed",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "Jd6pmOxzCXQ",
    "title": "1997 Nabisco Commercial: Flying Oreos and Talk Back Pen - Aired April 1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "XLi273N3oB0",
    "title": "Zeus and Roxanne TV Spot (1997) (windowboxed)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "XKmWa7X6hi8",
    "title": "Les Miserables Movie Trailer 1998 - TV Spot",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "tCQcmz7Ki0E",
    "title": "Maggie - 1998 TV Show (Episode 7 - \"The Maris Syndrome\")",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "D5BCgHXGiLs",
    "title": "Malcolm's Older Brother Visits | Malcolm & Eddie | Throwback TV",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "EpklDITQnQM",
    "title": "Compaq 1998 Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "FTqgpQJkefo",
    "title": "Dr. Bombay - S.O.S (The Tiger Took My Family)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "h18bDO8TvEI",
    "title": "Ray Harryhausen Week Sci-Fi Channel TV Ad (1998)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "aryVmYT-BfE",
    "title": "Testimony - Divas Live 1998",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "ZzJKOsLJbeY",
    "title": "Ultraspank - Five - Live @ Palladium ★ 11-15-1998 ★ [1/7]",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "94J0QcQkE80",
    "title": "BILLY ZANE - TITANIC",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "huGwqrJ5peg",
    "title": "Beloved Movie Trailer 1998 - TV Spot",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "5qzLtYbaGKM",
    "title": "My Party with Barney",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "TtkKF4QuBBc",
    "title": "Artisan Home Entertainment Home Video Rental VHS Promo (1998)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "W5UfwtTvu0Q",
    "title": "RoboCop Alpha Commando - 18 - Oh Tannenbaum Whoa Tannenbaum",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "qW5dr9JiUG4",
    "title": "1990's TV Commercials: Volume 247",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "07mX1qnn2LE",
    "title": "Pearl Jam: Live on Two Legs Music Album Ad (1998)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "SH-nkvXiiis",
    "title": "KPRC/NBC News 2 Houston at Noon circa November 1, 1999 (FULL)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "NiF6-0UTqtc",
    "title": "Destiny's Child - Bills, Bills, Bills",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "zFwR71GuRYY",
    "title": "ATWT 3 9 99",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "CGr8pEOGA4I",
    "title": "1999 Advil Liqui-gels \"Stronger and faster\" TV Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "TSeZN4B5sJE",
    "title": "Percy the Park Keeper - The Rabbit Who Was Afraid of the Dark (1999)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "vBZBStXjbks",
    "title": "ATWT 5 21 99",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "i8U5uSJf1ac",
    "title": "Pokemon: Snap Nintendo 64 N64 Video Game Ad (1999)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "dawy1P-c94A",
    "title": "The Theory of Flight Pay-Per-View Ad (1999)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "Kt6JI9gzECo",
    "title": "1999 Corn Pops Commercial (Aaron Paul)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "6So8edm688k",
    "title": "Universal Hits - Get Lucky Contest (1999) Promo (VHS Capture)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "L0SdLsFQ5XI",
    "title": "Gregorian - Tears In Heaven (Masters Of Chant in Santiago De Compostela)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "58FSVWBN4n4",
    "title": "1999   Falcons-Bengals Preseason Highlights   September 3",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "Ff5ohf-ii5s",
    "title": "Ghetty Green",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "jsDmWVhIu2I",
    "title": "WWC 1999 CANvsRUS group stage",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Trailers",
    "video_id": "PDoN_oPLU4g",
    "title": "Mr  X & Mr  Y   New world order         VIVA  VHS",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "OatUMBSDQyo",
    "title": "75 minutes of late 90s nostalgia - 1990s Commercial Compilation #50",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "PKBwVEJnXKk",
    "title": "70 Minutes of Decade Defining 1990s TV Commercials 🔥📼  Retro Commercials VOL 513",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "oemoqEuJdFE",
    "title": "Over Four Hours of 1990s Commercials",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "cHB-SXuR_iY",
    "title": "Every 90s Commercial",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "4cf3NRj4sXg",
    "title": "Only 90s & 2000s Kids Will Remember These Ads",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "GLbzveWbrSE",
    "title": "Random 90’s Commercials",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "RUCVnK8DvVA",
    "title": "1997 Nickelodeon TV Commercials - 90s Commercial Compilation #33",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "-w12KiZtnII",
    "title": "90s Commercials Were INSANE #nostalgia #90skids #retro #90slife #retrorecall",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "xR3Pq8VY8R8",
    "title": "3+ hours of Halloween TV commercials from the ‘90s | 1990s holiday nostalgia ambience",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "7OqEDrMCOQI",
    "title": "Epic Huge 80s/Early 90s Commercial Mix",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "xxuihEYl65o",
    "title": "90s Commercials Marathon - Over 1 Hour of Vintage TV Ads 📺📼 V601",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "P-z3ZuR4lwo",
    "title": "*1990* CORN POPS commercial featuring Paul Walker• #90s #nostalgia",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "GhmuKaJI_c8",
    "title": "90s Ad Jingles You'll be Singing All Day #90snostalgia #oscarmayer",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "ymcBgDX8Sgs",
    "title": "Grey Poupon - 1994 #1990scommercials #1990s #1990snostalgia",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "y4yo6n7XHZ8",
    "title": "90s honey comb commercial #90s #90snostalgia #90sthrowback #90scommercials #nostalgia #nostalgic",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "7CXT_vISgFc",
    "title": "RAD 90s Toy Commercials!! (Vol. 1)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "RLbnAxes7E0",
    "title": "The best 90's Cereal Commercials (English TV Ads)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "CTY8hrvFck8",
    "title": "Surge Soda Commercial 1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Commercials",
    "video_id": "1shK-j_u6LI",
    "title": "\"The Showdown\" - Bird vs. Jordan McDonald's ad - 1993",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "XFkzRNyygfk",
    "title": "Radiohead - Creep",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "6NXnxTNIWkc",
    "title": "4 Non Blondes - What's Up (Official Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "TIy3n2b7V9k",
    "title": "Avril Lavigne - Sk8er Boi (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "5NPBIwQyPWE",
    "title": "Avril Lavigne - Complicated (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "6Whgn_iE5uc",
    "title": "Santana - Smooth (Official Video) ft. Rob Thomas",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "FRkev5Aooms",
    "title": "Missy Elliott - Hot Boyz [Official Music Video]",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "djV11Xbc914",
    "title": "a-ha - Take On Me (Official Video) [4K]",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "lAD6Obi7Cag",
    "title": "Dire Straits - Money For Nothing music video (Good quality, all countries)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "4VPpAZ9_qAw",
    "title": "Martina McBride - Independence Day (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "3IUlCNqAKKA",
    "title": "George Strait - I Cross My Heart (Official Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "hTWKbfoikeg",
    "title": "Nirvana - Smells Like Teen Spirit (Official Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "WQnAxOQxQIU",
    "title": "Savage Garden - Truly Madly Deeply (Official Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "w7y19ED6Vrk",
    "title": "Kiss From A Rose - Seal lyrics",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "ah5gAkna3jI",
    "title": "Gin Blossoms - Hey Jealousy (Official Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "NPcyTyilmYY",
    "title": "Alanis Morissette - You Oughta Know (Official 4K Music Video)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "eVTXPUF4Oz4",
    "title": "In The End [Official HD Music Video] - Linkin Park",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "7W3DoubNtE4",
    "title": "Dance Hits 1990: Ft. Madonna, Deee-Lite, Kylie Minogue, Roxette, MC Hammer, Nick Kamen, DNA + more!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Music",
    "video_id": "9AdBRzJLTdg",
    "title": "90s - 2000s Throwback Hip Hop Rap Video Mix - Dj Presley Ft Dmx, 50 cent JayZ Nelly Ja Rule Ludacris",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "ts7--zxXXKQ",
    "title": "Goof troop theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "CMU2NwaaXEA",
    "title": "Duck Tales Theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "eLA8lIvOCwQ",
    "title": "Every 90s Cartoon Intro - Part 1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "EwBX_9SXAJw",
    "title": "Best 90's Cartoon Intros - Classic TV",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "jMEj9kQg3F8",
    "title": "\"Rugrats\" Theme Song (HQ) | Episode Opening Credits | Nick Animation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "Z2EotmVUdDE",
    "title": "\"Hey Arnold!\" Theme Song (HQ) | Episode Opening Credits | Nick Animation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "_iD5x08YDnQ",
    "title": "Every 90s Cartoon Intro - Part 2",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "kY53nXOGOz0",
    "title": "90's Cartoon Intro Compilation Part 3",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "M-J4Myp-7Zk",
    "title": "Bobby's World Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "OiYjTb3opAA",
    "title": "Captain Planet - Intro Theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "2b2imSfOqSA",
    "title": "🎶 Guess the 90s Cartoon Intro Theme Songs in 6 Seconds! - Ultimate Nostalgia Quiz 🎶",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "YjWf0NwUoBo",
    "title": "\"All Grown Up!\" Theme Song (HQ) | Episode Opening Credits | Nick Animation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "6usFrcdtUzE",
    "title": "The Amanda Show Opening (Season's 2-3)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "wL2xAvdVL1Y",
    "title": "Top 25 80s childrens tv intros (Re-Upload)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "fp7KLqiFWEM",
    "title": "Top 10 Best 90s Cartoon Theme Songs",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "dylX-4mljcE",
    "title": "Nickelodeon old theme song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Cartoons",
    "video_id": "W9_so_YiaBg",
    "title": "EVERY Cartoon Network Original opening title 1993-2023 | Cartoon Network UK",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "Jd8iuHOqn3A",
    "title": "The 90's movie trailer compilation pt1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "40hHA9n4C2o",
    "title": "Devil's Advocate (1997) Official Trailer - Al Pacino, Keanu Reeves Drama Movie HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "E6Xf65X0JB8",
    "title": "The Lost World: Jurassic Park Official Trailer #1 - Jeff Goldblum Movie (1997) HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "PPwyhTwp8Xs",
    "title": "THE BEST OF.... 90's movies Trailers",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "CK2Btk6Ybm0",
    "title": "Home Alone Trailer",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "73ax6ZrcUx4",
    "title": "(Original 1996) James And The Giant Peach Trailer",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "0PGWbYA3UWo",
    "title": "90s Action Movie Trailers Part 1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "CRRlbK5w8AE",
    "title": "Terminator 2: Judgment Day (1991) Trailer #1 | Movieclips Classic Trailers",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "ZgHPumVN4Fo",
    "title": "Point Break (1991) Trailer #1 | Movieclips Classic Trailers",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "O3gEDCS1O5Q",
    "title": "The Deep End of the Ocean Trailer (1999 Movie Trailer) Michelle Pffeifer",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "iUIAxTxrnCc",
    "title": "The Crucible Movie Trailer (1996) Rare Trailer - Winona Ryder, Daniel Day-Lewis",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "iIPB4GWGxSc",
    "title": "Best of the 90s Film Trailers | MGM Studios Compilation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "WR45uKBPkbc",
    "title": "1990 Movie TV Spots (Trailers) Compilation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "oKNy-MWjkcU",
    "title": "Space Jam (1996) Official Trailer - Michael Jordan, Bill Murray Movie HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "D7tpKFqf4po",
    "title": "Ri¢hie Ri¢h (1994) Official Trailer - Macaulay Culkin, John Larroquette Movie HD",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Movies",
    "video_id": "w9Rx6-GaSIE",
    "title": "Mid90s | Official Trailer HD | A24",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "E7mMhPNpSiM",
    "title": "NBA Greatest Plays of the 1990s!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "OEGpmzHaykI",
    "title": "60 Plays From the 90s That Would Break the Internet Today 🤯",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "fRFD4VNrcIk",
    "title": "The Greatest Era In NBA History (Entire 1990's Recap)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "-pGxakorTQY",
    "title": "NB90's [Complete]",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "DiqEfbA6200",
    "title": "Ranking the Best 90s NBA Highlights🔥",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "4Rxl79oqZgA",
    "title": "Top 10 NBA Players of the 90s",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "dMQ5mXOSNZw",
    "title": "90's DEFENSE 😤 #shorts",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "X2p8R1nVFG0",
    "title": "Top 10 NBA Players From The 90’s!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "-7XwrhSAxcc",
    "title": "🔥 90s Playoff Basketball Intensity",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "OjQju8Ue7bQ",
    "title": "NB90's Greatest Hits (Full Episode Compilation)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "wOhqPjKZjzY",
    "title": "Penny Hardaway Had the Filthiest Highlights of the 90s",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "ZUF_up90j9o",
    "title": "\"The '90s Steph\" Mahmoud Abdul-Rauf Drops 51 Pts, 9 Threes vs Jazz 😲",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "iDaOuPHHPvY",
    "title": "How Physical Was Basketball in the 90s?",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "OHSD7B6zCxY",
    "title": "12 Best NBA DUNKS OF THE 90s #bballshorts #nbashorts",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "3EnuT5Y0SbE",
    "title": "modern nba defense vs 90s",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "bWhOTQO0PHo",
    "title": "1990s rushing yard leaders!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Sports",
    "video_id": "9xR5ujOIOF0",
    "title": "Daewon Song - Trilogy",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "d-OrHsG-03I",
    "title": "Full House Season Eight Extended Theme Song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "1nCqRmx3Dnw",
    "title": "The Fresh Prince Of Bel Air Theme Song (Full)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "_iAQCeV5VIM",
    "title": "Guess The 90s TV Show Theme Song!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "g_6fl-kMw4U",
    "title": "Best sitcom intros of the 90's!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "yYlD7mK8RFA",
    "title": "90s Black Sitcoms Theme Song Challenge",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "Niu9Zmrx0p8",
    "title": "FRIENDS - Theme Song (Intro)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "Zx3Zo9t7c8Q",
    "title": "Full House - Theme Song [Full Version]",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "X43K__0f6gA",
    "title": "My Saved by the Bell Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "W2UFFzPsSsg",
    "title": "Darkwing Duck: The Original Theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "kF4H5vZ-Km4",
    "title": "Martin - Seasons 1 & 2 - Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "LICew-bwFHM",
    "title": "Martin - Season 3 - Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "h-mi0r0LpXo",
    "title": "Cheers intro song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "vgmiBjJFOSA",
    "title": "The Munsters Opening (in COLOR) - POP-COLORTURE.com",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "MYcqToQzzGY",
    "title": "The JeffersonsTheme Song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "zkD9wzrrhiA",
    "title": "Who's the Boss Opening Credits and Theme Song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Comedy",
    "video_id": "zCimIjkjMvA",
    "title": "‘Yes, yes, I remember. I had lasagna.’ #comedy #shorts",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "u5eGqrUN2zA",
    "title": "NBC News Today (January 1, 1990)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "APyfEY814-w",
    "title": "Headline News - October 16, 1992",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "poywry4QZVM",
    "title": "Timeline: The 90s - Everything That Happened In The 90s | Compilation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "6Nlqb4Kc0iA",
    "title": "1990s Local News Broadcast Compilation | VHS TV Nostalgia | Vintage TV | Pure Retro TV Nostalgia",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "9uUAv0V_aMQ",
    "title": "Timeline TV: The 90s - Everything That Happened In TV In The 90s | Compilation",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "ASuG1MPMwBw",
    "title": "Late 90s KTVU News Clips and Retro Commercials",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "u5WGx1LvSuY",
    "title": "BBC News titles 1990",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "ObqK-8ONQ4w",
    "title": "Millennial Reacts to 60 Plays From the 90s That Would Break the Internet Today! | NBA Michael Jordan",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "4uLftKfECUI",
    "title": "Tuje Sang Preet Lagai Sajna | 90's Romantic Hindi Song | Bollywood Love Song | #ytshorts #OldIsGold",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "AeRTwWCCRaA",
    "title": "One hour of late 90s basic cable TV commercials - 1990s Commercial compilation #49",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "Py7STWLBpz8",
    "title": "These Are Some of the Biggest News Stories of the 1990s",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "LBTlW62BS4g",
    "title": "News Broadcast 90s Decade",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "TDrQzOV_JIU",
    "title": "I Made a FULL Newscast from 1990 w/COMMERCIALS!!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "-fsD19FMdCE",
    "title": "Warning: These ‘90s TV Ads May Cause Nostalgia Whiplash 📺📼 V577",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "NSUjXhWuGSc",
    "title": "Best TV News Bloopers Of The Decade",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "News",
    "video_id": "EDXpyvEB6go",
    "title": "BBC News 1990s Intros",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "AsSzXq34ysg",
    "title": "Blockbusters - Theme Song (U.K)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "m2VDjPWomHU",
    "title": "family fortunes 1993 (opening theme)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Na-ShvC7f0M",
    "title": "Wheel of Fortune - 1975 theme, 1979 wheel",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "wf37Dgj92QM",
    "title": "Stereo Theme Of Wheel Of Fortune 1983-1989 \"Changing Keys\"",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "oA3efell-Zo",
    "title": "Guess The 90s Cartoon Theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "yXSCzZbP_O0",
    "title": "What Would You Do? Opening Theme Song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "gkvEb3iVQz0",
    "title": "90s TV Show Theme Song Quiz | WARNING - HARD!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "8F3Bw5dYZAM",
    "title": "Guess The 90s TV Show Theme Song Quiz - 100 Series!",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Y6rHqrLA7aw",
    "title": "Jeopardy! Theme, 1984-1991",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "aiyd0mZnix8",
    "title": "Jeopardy! Tournament Theme 1992-1997",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Dqi8Qh6jmk4",
    "title": "Jackpot 1974-1975 theme music",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "c3O6-CHQLgs",
    "title": "Stereo Theme of The $10,000/$20,000/$25,000 Bill Cullen Pyramids",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "8V-Vw863f1M",
    "title": "1990s UK Game Shows Theme Tune Quiz Part 1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "Hi6SDg79d0k",
    "title": "90s Game Show Theme | Music for content creator",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "d2JooUMsDdA",
    "title": "The Brady Bunch Theme Song Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "BJejtgnFWWc",
    "title": "Nickelodeon GUTS - Intro Theme (1992, HQ)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "Gameshows",
    "video_id": "MhMNxncu5Gg",
    "title": "Supermarket Sweep (1994) (full game)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "fJLh7J2egOc",
    "title": "90's Classic TV Shows - Intros Openings & Themes (HD)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "xjhcr_VYq24",
    "title": "30 '90s TV Show Opening Themes",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "0MhTH8h9T9I",
    "title": "ABC - \"TGIF Tribute\" - TV Theme Songs - 1980s, 1990s, 2000s - TV Show Openings - Theme Song Credits",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "9DAORNCSkGc",
    "title": "The Secret World of Alex Mack - Opening",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "dZIFllFBGFg",
    "title": "1980s - MOST POPULAR TV INTROS OPENINGS OF THE 80s (HD)",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "TP5Dhz1LXUg",
    "title": "Combat Opening Theme",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "g6kqGaEj2fg",
    "title": "Thundercats opening theme song",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "_AIFoBRIny0",
    "title": "Transformers Cartoon Intro Theme Song 1980's Season 1",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "qmntt_9S51k",
    "title": "90s Sitcom Intros",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "myBm7xeBSSI",
    "title": "TV Intros from the 90s You Can Still Sing by Heart",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "lw6MHQ_2kQk",
    "title": "90s TV Shows Theme Songs / Intros #90s #90stvshows #shorts",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "_1dberGgTYY",
    "title": "90's TV Show Intros #shorts #90s",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "cJwMGdNsjgU",
    "title": "Typical 90's Sitcom Intro.",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "D9QtPCEsdkY",
    "title": "Top 10 Best 90s TV Theme Songs",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "CikKn24ZD4k",
    "title": "That '90s Show - Classic Intro",
    "start_seconds": "0",
    "end_seconds": "0"
  },
  {
    "decade": "1990s",
    "year": "1995",
    "channel": "TV Intros",
    "video_id": "7SqBC7R77rs",
    "title": "Every 90s Sitcom Intro Ever🤣#shorts #90s",
    "start_seconds": "0",
    "end_seconds": "0"
  }
];
